#!/bin/bash
# ------------------------------------------------------------------
#
#     Scripts/spaceperc
#     Description: Script for piping the free space status into dzen
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

FREE=`df /home -h | awk 'END{gsub(/%/,""); print $5}'`

ICON="diskette.xbm"
if [[ $FREE -gt 90 ]]; then
    PERCBAR=`echo -e "$FREE"`
    ICON='^fg(red)^i(/home/alex/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
else
    PERCBAR=`echo -e "$FREE"`
    ICON='^i(/home/alex/.xmonad/dzen/icons/xbm8x8/'"$ICON)"
fi

echo "$ICON $PERCBAR"
