#!/bin/bash
# ------------------------------------------------------------------
#
#     batinfo
#     Description: Script for piping the current battery status to bar
#     Author: Alex Sánchez <kniren@gmail.com>
#
# ------------------------------------------------------------------

while true; do
    BAT=`acpi -b | grep "Battery 1" | cut -d " " -f4 | tr -d '%' | tr -d ','`
    STAT=`acpi -b | grep "Battery 1" | cut -d " " -f3 | tr -d '%' | tr -d ','`
    PREFIX="H"
    if [[ "$BAT" -lt 50  ]]; then
        PREFIX="M"
    fi
    if [[ $BAT -lt 20  ]]; then
        PREFIX="L"
    fi
    if [[ $BAT -lt 10  ]]; then
        PREFIX="R"
    fi
    if [[ $STAT != "Discharging" ]]; then
        PREFIX="C"
    fi
    echo B$PREFIX$BAT 
    sleep 1
done
