#! /bin/sh

bspc config border_width            2
bspc config window_gap              20

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config auto_cancel             true
bspc config normal_frame_opacity    0.0
bspc config focused_frame_opacity   0.1

bspc monitor -d          

# To extract the windows name use: xprop | grep WM_CLASS
bspc rule -a Google-chrome-stable desktop=^2
bspc rule -a mplayer2 floating=on

panel &
