#!/bin/bash

PANEL_HEIGHT=20
PANEL_FIFO=/tmp/panelfifo
FONT1="-*-profont-*-*-*-*-10-*-*-*-*-*-*-*"
FONT2="-*-stlarch-*-*-*-*-10-*-*-*-*-*-*-*"

. panel_colors

if [ $(pgrep -cx panel) -gt 1 ] ; then
        printf "%s\n" "The panel is already running." >&2
            exit 1
        fi

        trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

        [ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
        mkfifo "$PANEL_FIFO"

        bspc config top_padding $PANEL_HEIGHT
        bspc control --subscribe > "$PANEL_FIFO" &
        clock -sf "S%{F$COLOR01} %Y-%m-%d%{F$COLOR03} %H:%M" > "$PANEL_FIFO" &
        netinfo > "$PANEL_FIFO" &

cat "$PANEL_FIFO" | panel_bar | bar -g x$PANEL_HEIGHT -f "$FONT1","$FONT2" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
