#!/bin/bash
#
# Example panel for LemonBoy's bar

. panel_colors

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        # Battery
        B*) 
        bat=${line#?}
        case $bat in
            H*) 
                # Discharging bat > 50%
                baticon="  "
                ;;
            M*)
                # Discharging 50% > bat > 20%
                baticon="  "
                ;;
            L*)
                # Discharging 20% > bat > 10%
                baticon="  "
                ;;
            R*)
                # Discharging 10% > bat > 0% critical
                baticon="  "
                ;;
            C*)
                # Charging
                baticon="  "
                ;;
        esac
        bat="%{F$COLOR02} $baticon ${bat#?}%{B-}%{F-}"
        ;;
        # Net info
        N*)
        net="%{F$COLOR01}  ${line#?}%{B-}%{F-}"
        ;;
        # Clock and date
        S*)
        # clock output
        sys_infos="%{F$COLOR03}  ${line#?} %{B-}%{F-}"
        ;;
    W*)
        # bspwm internal state
        wm_infos=""
        IFS=':'
        set -- ${line#?}
        while [ $# -gt 0 ] ; do
            item=$1
            name=${item#?}
            case $item in
                [OFU]*)
                    # focused occupied desktop
                    wm_infos="${wm_infos}%{F$COLOR_FOCUSED_OCCUPIED_FG}%{U$COLOR_FOREGROUND}%{+u}  %{-u}%{B-}%{F-}"
                    ;;
                o*)
                    # occupied desktop
                    wm_infos="${wm_infos}%{F$COLOR_OCCUPIED_FG}  %{B-}%{F-}"
                    ;;
                f*)
                    # free desktop
                    wm_infos="${wm_infos}%{F$COLOR_FREE_FG}  %{B-}%{F-}"
                    ;;
                u*)
                    # urgent desktop
                    wm_infos="${wm_infos}%{F$COLOR_URGENT_FG}  %{B-}%{F-}"
                    ;;
            esac
            shift
        done
        ;;
esac
printf "%s\n" "%{l}${net}%{c}${wm_infos}%{r}${bat} ${sys_infos}"
done
